---
- name: "Load phase coverage role context"
  ansible.builtin.include_role:
    name: "{{ _phase_coverage_role_path }}"
    tasks_from: "common/load-context.yml"
  vars:
    archivematica_upgrade_es6_checksum: "{{ _phase_coverage_es6_checksum }}"
