---
- name: "Run Archivematica upgrade phase file {{ _phase_coverage_phase_file }}"
  ansible.builtin.include_role:
    name: "{{ _phase_coverage_role_path }}"
    tasks_from: "phases/{{ _phase_coverage_phase_file }}.yml"
  vars:
    archivematica_upgrade_es6_checksum: "{{ _phase_coverage_es6_checksum }}"
